apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remote-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "remoteapp.msawan.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: remote-app-service
            port:
              number: 80
