name: Certificate Management on Kubernetes
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Do you want to deploy changes'
        required: true
        default: 'true'
jobs:

  Certificate_Management_on_Kubernetes:
     name: Build, push, and deploy
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout master
       uses: actions/checkout@master
     
     - name: Install doctl
       uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
 
     - name: Save DigitalOcean kubeconfig with short-lived credentials
       run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
       
     - name: Deploy Cert-Manager to DigitalOcean Kubernetes
       run: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml

     - name: Deploy Certificate Issuer to DigitalOcean Kubernetes
       run: kubectl apply -f $GITHUB_WORKSPACE/deploy/cert-issuer.yml

     - name: Enable Pod to Pod Communication to DigitalOcean Kubernetes
       run: kubectl apply -f $GITHUB_WORKSPACE/deploy/pod_to_pod.yml
